[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
solsplit = "9wjqD7c7AR8BttsmdKShzraGvC2zUqMbmmDLKTykxhi7"

[programs.localnet]
solsplit = "9wjqD7c7AR8BttsmdKShzraGvC2zUqMbmmDLKTykxhi7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
